### ISSUE TITLE
Getting Fatal error on PHP 8.1 with this module enabled

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/match_redirect#10]
I originally thought the issue was with entity_plus and raised [an issue there](/backdrop-contrib/entity_plus/issues/166) but have since tracked down to this module.

<details>
<summary>Stack trace</summary>

```
Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /app/docroot/modules/contrib/entity_plus/entity_plus.module:994 
Stack trace: 
#0 /app/docroot/modules/contrib/entity_plus/entity_plus.module(994): in_array('EntityPlusContr...', false) 
#1 /app/docroot/core/includes/theme.inc(558): entity_plus_theme(Array, 'module', 'entity_plus', 'modules/contrib...') 
#2 /app/docroot/core/includes/theme.inc(715): _theme_process_registry(Array, 'entity_plus', 'module', 'entity_plus', 'modules/contrib...') 
#3 /app/docroot/core/includes/theme.inc(355): _theme_build_registry(Object(stdClass), Array, 'phptemplate') 
#4 /app/docroot/core/includes/theme.inc(304): _theme_load_registry(Object(stdClass), Array, 'phptemplate') 
#5 /app/docroot/core/includes/theme.inc(440): theme_get_registry() 
#6 /app/docroot/core/includes/theme.inc(424): ThemeRegistry->initializeRegistry() 
#7 /app/docroot/core/includes/theme.inc(365): ThemeRegistry->__construct('theme_registry:...', 'cache') 
#8 /app/docroot/core/includes/theme.inc(304): _theme_load_registry(Object(stdClass), Array, 'phptemplate', false) 
#9 /app/docroot/core/includes/theme.inc(1024): theme_get_registry(false) 
#10 /app/docroot/core/includes/errors.inc(256): theme('maintenance_pag...', Array) 
#11 /app/docroot/core/includes/bootstrap.inc(2989): _backdrop_log_error(Array, true) 
#12 [internal function]: _backdrop_exception_handler(Object(TypeError)) 
#13 {main} thrown in /app/docroot/modules/contrib/entity_plus/entity_plus.module on line 994
```

</details>

Also got warning which helped me track the issue to this module:

Warning: class_implements(): Class MatchRedirectEntityController does not exist and could not be loaded in entity_plus_theme() (line 994 of /app/docroot/modules/contrib/entity_plus/entity_plus.module).

**Comment by argiepiano** [comment]
I don't see anything wrong with this module that may be producing this error. More likely, this is being produced by an unrelated error which triggers a whole chain of events, that ends up with a theme registry rebuild before autoload hooks load. Entity Plus, unfortunately, needs to know if the entity controller classes are derivatives of its own controller. To do that, it calls `class_implements()`. But since autoload hooks haven't run, this (and other) controller classes are not available - leading to the error that @yorkshire-pudding is seeing.

I believe it's safe to close this issue, and focus on catching this with Entity Plus, and also fix the initial error that triggers all this.

**Comment by yorkshire-pudding** [comment]
Closing then
